CREATE VIEW TMP AS
SELECT F1.USER1_ID AS COMMON_ID, F1.USER2_ID AS USER1_ID, F2.USER2_ID AS USER2_ID
FROM project2.PUBLIC_FRIENDS F1, PROJECT2.PUBLIC_FRIENDS F2
WHERE F1.USER1_ID = F2.USER1_ID
UNION
SELECT F1.USER2_ID, F1.USER1_ID, F2.USER1_ID
FROM project2.PUBLIC_FRIENDS F1, PROJECT2.PUBLIC_FRIENDS F2
WHERE F1.USER2_ID = F2.USER2_ID
UNION
SELECT F1.USER1_ID, F1.USER2_ID, F2.USER1_ID
FROM project2.PUBLIC_FRIENDS F1, PROJECT2.PUBLIC_FRIENDS F2
WHERE F1.USER1_ID = F2.USER2_ID;

CREATE VIEW TMP2 AS
SELECT DISTINCT *
FROM (TMP UNION ALL
SELECT COMMON_ID, USER2_ID, USER1_ID
FROM TMP) T
WHERE T.USER1_ID < T.USER2_ID
;

CREATE VIEW Q6 AS
SELECT * FROM(
SELECT USER1_ID, USER2_ID FROM TMP2 T
GROUP BY (USER1_ID, USER2_ID)
ORDER BY COUNT(COMMON_ID) DESC, USER1_ID, USER2_ID)
WHERE ROWNUM <= K;  -- K is what we define outside

CREATE VIEW PIKA AS
TMP2 T INNER JOIN Q6 q ON T.USER1_ID = Q.USER1_ID AND T.USER2_ID = Q.USER2_ID;

SELECT U2.USER_ID, U2.FIRST_NAME, U2.LAST_NAME, U3.USER_ID, U3.FIRST_NAME, U3.LAST_NAME, U1.USER_ID, U1.FIRST_NAME, U1.LAST_NAME
FROM pika q, project2.PUBLIC_USERS U1, PROJECT2.PUBLIC_USERS U2, PROJECT2.PUBLIC_USERS U3
WHERE U1.USER_ID =  Q.COMMON_ID AND U2.USER_ID = Q.USER1_ID AND U3.USER_ID = Q.USER2_ID;